### ISSUE TITLE
cannot install with Python 3.6

### ISSUE THREAD

**Issue by krober10nd** [noaa-ocs-modeling/adcircpy#137]
Cloning the latest head and installing locally. 

Also strangely, I installed the v1.0.40 from pip and it did not contain some of the latest fixes to the HEAD. For example, the `import_nodal_attribute`  does not contain the `enable` kwarg despite it being present on HEAD. 

```
➜  adcircpy git:(main) pip3 install -e .
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///mnt/c/Users/kroberts/codes/my_codes/adcircpy
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/kroberts/codes/my_codes/adcircpy/setup.py'"'"'; __file__='"'"'/mnt/c/Users/kroberts/codes/my_codes/adcircpy/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nasebl4t
         cwd: /mnt/c/Users/kroberts/codes/my_codes/adcircpy/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/c/Users/kroberts/codes/my_codes/adcircpy/setup.py", line 64, in <module>
        if 'dunamai' not in installed_packages():
      File "/mnt/c/Users/kroberts/codes/my_codes/adcircpy/setup.py", line 40, in installed_packages
        f'{sys.executable} -m pip freeze', shell=True, capture_output=True,
      File "/usr/lib/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
    TypeError: __init__() got an unexpected keyword argument 'capture_output'
    ----------------------------------------
WARNING: Discarding file:///mnt/c/Users/kroberts/codes/my_codes/adcircpy. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
➜  adcircpy git:(main)
```

**Comment by krober10nd** [comment]
this is related to using Python 3.6

**Comment by krober10nd** [comment]
https://stackoverflow.com/questions/53209127/subprocess-unexpected-keyword-argument-capture-output/53209196

**Comment by ghost** [comment]
I apologize for not getting to this issue promptly. Since `v1.0.44`, `setup.py` uses `importlib_metadata` instead of `subprocess.run('pip freeze')`, and this seems to work on Python 3.6. 

Which version are you using currently? If the issue is with pandas dataframes, I could probably add a compatibility patch to make it work with your workflow.
